import { logger } from '@/libs/logger';

const checkEnv = (key: string) => {
	const value = Bun.env[key];

	if (!value) {
		logger.error(`Missing required environment variable: ${key}`);
		throw new Error(`Missing required environment variable: ${key}`);
	}
	return value;
};

export const ENV = {
	NODE_ENV: checkEnv('NODE_ENV'),

	PORT: checkEnv('PORT'),

	ACCESS_TOKEN_SECRET: checkEnv('ACCESS_TOKEN_SECRET'),
	REFRESH_TOKEN_SECRET: checkEnv('REFRESH_TOKEN_SECRET'),
	ACCESS_TOKEN_EXPIRY: checkEnv('ACCESS_TOKEN_EXPIRY'),
	REFRESH_TOKEN_EXPIRY: checkEnv('REFRESH_TOKEN_EXPIRY'),

	BACKEND_ORIGIN: checkEnv('BACKEND_ORIGIN'),

	REDIS_HOST: checkEnv('REDIS_HOST'),
	REDIS_PORT: checkEnv('REDIS_PORT'),

	REDIS_PUBSUB_HOST: checkEnv('REDIS_PUBSUB_HOST'),
	REDIS_PUBSUB_PORT: checkEnv('REDIS_PUBSUB_PORT'),

	RESEND_API_KEY: checkEnv('RESEND_API_KEY'),

	GOOGLE_CLIENT_ID: checkEnv('GOOGLE_CLIENT_ID'),
	GOOGLE_CLIENT_SECRET: checkEnv('GOOGLE_CLIENT_SECRET'),
	GOOGLE_REDIRECT_URI: checkEnv('GOOGLE_REDIRECT_URI'),

	DISCORD_CLIENT_ID: checkEnv('DISCORD_CLIENT_ID'),
	DISCORD_CLIENT_SECRET: checkEnv('DISCORD_CLIENT_SECRET'),
	DISCORD_REDIRECT_URI: checkEnv('DISCORD_REDIRECT_URI'),

	TELEGRAM_BOT_TOKEN: checkEnv('TELEGRAM_BOT_TOKEN'),

	TWILIO_SID: checkEnv('TWILIO_SID'),
	TWILIO_TOKEN: checkEnv('TWILIO_TOKEN'),
	TWILIO_NUMBER: checkEnv('TWILIO_NUMBER'),

	AWS_REGION: checkEnv('AWS_REGION'),
	AWS_S3_BUCKET: checkEnv('AWS_S3_BUCKET'),
	AWS_ACCESS_KEY_ID: checkEnv('AWS_ACCESS_KEY_ID'),
	AWS_SECRET_ACCESS_KEY: checkEnv('AWS_SECRET_ACCESS_KEY'),

	CASHFREE_CLIENT_ID: checkEnv('CASHFREE_CLIENT_ID'),
	CASHFREE_CLIENT_SECRET: checkEnv('CASHFREE_CLIENT_SECRET'),
	CASHFREE_PAYOUT_CLIENT_ID: checkEnv('CASHFREE_PAYOUT_CLIENT_ID'),
	CASHFREE_PAYOUT_CLIENT_SECRET: checkEnv('CASHFREE_PAYOUT_CLIENT_SECRET'),

	NOTIFICATION_WORKER_URL: checkEnv('NOTIFICATION_WORKER_URL'),
	WORKER_SECRET: checkEnv('WORKER_SECRET'),

	GMAIL_USER: checkEnv('GMAIL_USER'),
	GMAIL_APP_PASSWORD: checkEnv('GMAIL_APP_PASSWORD'),
};
