export const DB_EVENTS = {
	INCREASE_TRADERS_COUNT: 'INCREASE_TRADERS_COUNT',
	UPDATE_STOCK_PRICE: 'UPDATE_STOCK_PRICE',
	TRADE_EXECUTED: 'TRADE_EXECUTED',
	ORDER_PLACED: 'ORDER_PLACED',
	MARKET_RESOLVED: 'MARKET_RESOLVED',
	ORDER_CANCELLED: 'ORDER_CANCELLED',
	SHARES_SPLIT: 'SHARES_SPLIT',
	SHARES_MERGED: 'SHARES_MERGED',
	ARCHIVE_FAILED: 'ARCHIVE_FAILED',
} as const;
